# Generated by Django 3.2.13 on 2022-05-23 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='work_csv',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('csv_name', models.FileField(upload_to='data_csv/')),
            ],
        ),
    ]
